In [1]:
import pandas as pd
import numpy as np

In [2]:
!ls

Adnu_Analysis.ipynb			    adnu_order_items_dataset.csv
adnu_closed_deals_dataset.csv		    adnu_sellers_dataset.csv
adnu_marketing_qualified_leads_dataset.csv  marketing-funnel-adnu.zip

In [3]:
closed_deals = pd.read_csv('adnu_closed_deals_dataset.csv')
marketing_qualified_leads = pd.read_csv('adnu_marketing_qualified_leads_dataset.csv')
order_items = pd.read_csv('adnu_order_items_dataset.csv')
sellers_dataset = pd.read_csv('adnu_sellers_dataset.csv')

In [4]:
closed_deals.head()

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
0,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0
1,a555fb36b9368110ede0f043dfc3b9a0,bbb7d7893a450660432ea6652310ebb7,09285259593c61296eef10c734121d5b,d3d1e91a157ea7f90548eef82f1955e3,2018-05-08 20:17:59,car_accessories,industry,eagle,NaN,NaN,NaN,reseller,NaN,0.0
2,327174d3648a2d047e8940d7d15204ca,612170e34b97004b3ba37eae81836b4c,b90f87164b5f8c2cfa5c8572834dbe3f,6565aa9ce3178a5caf6171827af3a9ba,2018-06-05 17:27:23,home_appliances,online_big,cat,NaN,NaN,NaN,reseller,NaN,0.0
3,f5fee8f7da74f4887f5bcae2bafb6dd6,21e1781e36faf92725dde4730a88ca0f,56bf83c4bb35763a51c2baab501b4c67,d3d1e91a157ea7f90548eef82f1955e3,2018-01-17 13:51:03,food_drink,online_small,NaN,NaN,NaN,NaN,reseller,NaN,0.0
4,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,2018-07-03 20:17:45,home_appliances,industry,wolf,NaN,NaN,NaN,manufacturer,NaN,0.0

In [5]:
marketing_qualified_leads.head()

,mql_id,first_contact_date,landing_page_id,origin
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search

In [6]:
order_items.tail(10)

,order_id,order_item_id,product_id,seller_id,price,freight_value
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,55.00,34.19
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,119.85,20.03
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79

In [7]:
sellers_dataset.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [8]:
###SDR/SR optimization.We look at closed deals for this
closed_deals['sr_id'].value_counts()

4ef15afb4b2723d8f3d81e51ec7afefe    133
d3d1e91a157ea7f90548eef82f1955e3     82
6565aa9ce3178a5caf6171827af3a9ba     74
85fc447d336637ba1df43e793199fbc8     64
495d4e95a8cf8bbf8b432b612a2aa328     63
2695de1affa7750089c0455f8ce27021     59
fbf4aef3f6915dc0c3c97d6812522f6a     59
de63de0d10a6012430098db33c679b0b     53
9ae085775a198122c5586fa830ff7f2b     51
c638112b43f1d1b86dcabb0da720c901     36
060c0a26f19f4d66b42e0d8796688490     32
068066e24f0c643eb1d089c7dd20cd73     27
a8387c01a09e99ce014107505b92388c     26
56bf83c4bb35763a51c2baab501b4c67     24
9e4d1098a3b0f5da39b0bc48f9876645     24
34d40cdaf94010a1d05b0d6212f9e909     10
4b339f9567d060bcea4f5136b9f5949e      9
9749123c950bf8363ace42cb1c2d0815      7
9d12ef1a7eca3ec58c545c678af7869c      6
6aa3b86a83d784b05f0e37e26b20860d      1
b90f87164b5f8c2cfa5c8572834dbe3f      1
0a0fb2b07d841f84fb6714e35c723075      1
Name: sr_id, dtype: int64

In [9]:
closed_deals['sdr_id'].value_counts()

4b339f9567d060bcea4f5136b9f5949e    140
068066e24f0c643eb1d089c7dd20cd73     81
56bf83c4bb35763a51c2baab501b4c67     74
9d12ef1a7eca3ec58c545c678af7869c     66
a8387c01a09e99ce014107505b92388c     59
9e4d1098a3b0f5da39b0bc48f9876645     55
de63de0d10a6012430098db33c679b0b     53
370c9f455f93a9a96cbe9bea48e70033     51
f42a2bd194f7802ab052a815c8de65b7     42
09285259593c61296eef10c734121d5b     42
34d40cdaf94010a1d05b0d6212f9e909     41
fdb16d3cbbeb5798f2f66c4096be026d     34
0a0fb2b07d841f84fb6714e35c723075     25
b90f87164b5f8c2cfa5c8572834dbe3f     25
e7dff61b78bebffa71678e126ce669ad     13
45749fb708130f78d0db07d8d80f030b      8
9749123c950bf8363ace42cb1c2d0815      6
33dd30594303eb0ebe12a556d612c437      3
323cff2ceea1814239bc2c7e614d260d      3
2b63542749aa9caf15f21816da1db341      3
b34f6eba10f46bf9a657a01c108a8284      3
f6c6ab65a1c732f154b371401448be6d      3
0cdad77786224a7cefea567b8c75c3c1      2
6aa3b86a83d784b05f0e37e26b20860d      2
e4a6222cdb5b34375400904f03d8e6a5      1
9ae085775a198122c5586fa830ff7f2b      1
b1b3ec93fc27a19fdb1c1b1fc997776a      1
5b7ce8c2b0fe4c2f52a0763046914ef4      1
19f3cd308f1455b3fa09a282e0d496f4      1
084b6fbb10729ed4da8c3d3f5a3ae7c9      1
282f16e20d50cb18d05182e80f6b9dd6      1
6b13bcea409754a002210eb96b8aad4a      1
Name: sdr_id, dtype: int64

In [10]:
###lead behaviour profile
closed_deals['lead_behaviour_profile'].value_counts()

cat            407
eagle          123
wolf            95
shark           24
cat, wolf        8
eagle, wolf      3
eagle, cat       3
shark, cat       1
shark, wolf      1
Name: lead_behaviour_profile, dtype: int64

In [11]:
###Combining the rest of lead behaviour profile into others
cd_profile = closed_deals[closed_deals['lead_behaviour_profile'].notna()].copy()
profile_list = ['cat', 'eagle', 'wolf', 'shark']
cd_profile['lead_behaviour_profile'] = closed_deals['lead_behaviour_profile'].map(lambda profile: profile
                                                           if profile in profile_list
                                                           else 'others')

In [12]:
cd_profile['lead_behaviour_profile'].value_counts()

cat       407
eagle     123
wolf       95
shark      24
others     16
Name: lead_behaviour_profile, dtype: int64

In [13]:
cd_profile['lead_type'].value_counts()

online_medium      265
online_big         106
industry            94
offline             86
online_small        57
online_beginner     42
online_top          10
other                3
Name: lead_type, dtype: int64

In [14]:
cd_profile['business_type'].value_counts()

reseller        465
manufacturer    188
other             3
Name: business_type, dtype: int64

In [15]:
###SDR Performance by Behaviour Profile
cols = cd_profile['sdr_id'].value_counts().index
index = cd_profile['lead_behaviour_profile'].value_counts().index

profile_sdr = pd.pivot_table(cd_profile,
                             index='lead_behaviour_profile',
                             columns='sdr_id',
                             values='seller_id',
                             aggfunc='count',
                             fill_value=0)

In [16]:
profile_sdr = profile_sdr.reindex(index)[cols]
profile_sdr

sdr_id,4b339f9567d060bcea4f5136b9f5949e,9d12ef1a7eca3ec58c545c678af7869c,a8387c01a09e99ce014107505b92388c,9e4d1098a3b0f5da39b0bc48f9876645,068066e24f0c643eb1d089c7dd20cd73,370c9f455f93a9a96cbe9bea48e70033,09285259593c61296eef10c734121d5b,f42a2bd194f7802ab052a815c8de65b7,34d40cdaf94010a1d05b0d6212f9e909,56bf83c4bb35763a51c2baab501b4c67,...,33dd30594303eb0ebe12a556d612c437,b34f6eba10f46bf9a657a01c108a8284,0cdad77786224a7cefea567b8c75c3c1,6aa3b86a83d784b05f0e37e26b20860d,19f3cd308f1455b3fa09a282e0d496f4,084b6fbb10729ed4da8c3d3f5a3ae7c9,282f16e20d50cb18d05182e80f6b9dd6,5b7ce8c2b0fe4c2f52a0763046914ef4,e4a6222cdb5b34375400904f03d8e6a5,b1b3ec93fc27a19fdb1c1b1fc997776a
cat,52,35,50,37,43,26,25,23,30,24,...,3,1,2,1,1,1,0,1,0,0
eagle,9,22,4,10,3,14,8,7,8,16,...,0,0,0,0,0,0,0,0,0,0
wolf,42,6,3,3,3,7,7,7,1,0,...,0,0,0,0,0,0,1,0,0,0
shark,8,0,0,3,2,2,2,1,2,0,...,0,1,0,1,0,0,0,0,0,0
others,1,1,0,0,0,1,0,4,0,0,...,0,0,0,0,0,0,0,0,1,1

In [17]:
###Key take away on SDR on lead behaviour table
# - Top 5 SDR can handle cat category
# - 1 st SDR can handle wolf way better than any other
# - Eagle can be assigned to 2nd SDR and possibly 6th and 10th
# - 1st SDR can handle shark but is not an expert

In [18]:
# Create 'profile-SR' table
cols = cd_profile['sr_id'].value_counts().index
index = cd_profile['lead_behaviour_profile'].value_counts().index

sr_profile = pd.pivot_table(cd_profile,
                            index='lead_behaviour_profile',
                            columns='sr_id',
                            values='seller_id',
                            aggfunc='count',
                            fill_value=0)

sr_profile = sr_profile.reindex(index)[cols]
sr_profile

sr_id,4ef15afb4b2723d8f3d81e51ec7afefe,85fc447d336637ba1df43e793199fbc8,6565aa9ce3178a5caf6171827af3a9ba,d3d1e91a157ea7f90548eef82f1955e3,2695de1affa7750089c0455f8ce27021,de63de0d10a6012430098db33c679b0b,495d4e95a8cf8bbf8b432b612a2aa328,fbf4aef3f6915dc0c3c97d6812522f6a,068066e24f0c643eb1d089c7dd20cd73,c638112b43f1d1b86dcabb0da720c901,...,9e4d1098a3b0f5da39b0bc48f9876645,9ae085775a198122c5586fa830ff7f2b,56bf83c4bb35763a51c2baab501b4c67,34d40cdaf94010a1d05b0d6212f9e909,4b339f9567d060bcea4f5136b9f5949e,9749123c950bf8363ace42cb1c2d0815,9d12ef1a7eca3ec58c545c678af7869c,0a0fb2b07d841f84fb6714e35c723075,6aa3b86a83d784b05f0e37e26b20860d,b90f87164b5f8c2cfa5c8572834dbe3f
cat,58,41,31,28,34,37,30,30,11,17,...,16,12,17,3,7,2,3,1,0,0
eagle,23,7,13,12,9,7,6,9,7,5,...,6,4,2,4,0,0,0,0,0,1
wolf,12,11,11,11,6,5,7,2,4,3,...,0,5,2,0,2,4,1,0,0,0
shark,0,4,0,2,2,4,2,2,1,0,...,2,1,2,0,0,1,0,0,0,0
others,2,0,0,1,2,0,1,0,2,0,...,0,1,0,3,0,0,2,0,1,0

In [19]:
###Key takeaways on SR on lead behaviour table
# - First SR ('4ef15afb4b2723d8f3d81e51ec7afefe') can manage eagle and cat categories
# - All SR have their best at handling cat category
# - Top 4 SR can manage wolf, but not as good as their best
# - Top SR can manage eagle  way better than any other
# - Eagle can be assigned to 1st, 3rd or 4th SR

In [20]:
cols = cd_profile['sdr_id'].value_counts().index
index = cd_profile['lead_type'].value_counts().index

profile_sdr_leadtype = pd.pivot_table(cd_profile,
                             index='lead_type',
                             columns='sdr_id',
                             values='seller_id',
                             aggfunc='count',
                             fill_value=0)
profile_sdr_leadtype = profile_sdr_leadtype.reindex(index)[cols]
profile_sdr_leadtype

sdr_id,4b339f9567d060bcea4f5136b9f5949e,9d12ef1a7eca3ec58c545c678af7869c,a8387c01a09e99ce014107505b92388c,9e4d1098a3b0f5da39b0bc48f9876645,068066e24f0c643eb1d089c7dd20cd73,370c9f455f93a9a96cbe9bea48e70033,09285259593c61296eef10c734121d5b,f42a2bd194f7802ab052a815c8de65b7,34d40cdaf94010a1d05b0d6212f9e909,56bf83c4bb35763a51c2baab501b4c67,...,33dd30594303eb0ebe12a556d612c437,b34f6eba10f46bf9a657a01c108a8284,0cdad77786224a7cefea567b8c75c3c1,6aa3b86a83d784b05f0e37e26b20860d,19f3cd308f1455b3fa09a282e0d496f4,084b6fbb10729ed4da8c3d3f5a3ae7c9,282f16e20d50cb18d05182e80f6b9dd6,5b7ce8c2b0fe4c2f52a0763046914ef4,e4a6222cdb5b34375400904f03d8e6a5,b1b3ec93fc27a19fdb1c1b1fc997776a
online_medium,50,29,26,21,27,26,21,12,2,13,...,2,1,2,1,0,0,0,0,0,1
online_big,22,10,8,8,5,11,4,1,10,5,...,0,1,0,0,0,0,1,0,0,0
industry,19,9,6,5,8,6,5,4,7,7,...,0,0,0,0,0,0,0,0,0,0
offline,6,10,6,11,1,3,3,12,13,9,...,1,0,0,0,0,0,0,1,0,0
online_small,6,6,5,8,2,0,5,4,5,4,...,0,0,0,1,0,0,0,0,0,0
online_beginner,5,0,6,0,5,4,3,7,4,1,...,0,0,0,0,0,0,0,0,0,0
online_top,4,0,0,0,3,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,0

In [21]:
# ### Key takeaways from SDR on lead type
# - Top 6 SDR can work on online_medium. The first SDR is way ahead of other on this
# - First SDR is good on online_big.6 and 9 are also good on online_big
# - 1st SDR is way ahead of everybody in industry leads
# - 2,4,6,8 SDR works well in offline indusrty compared to rest

In [22]:
cols = cd_profile['sr_id'].value_counts().index
index = cd_profile['lead_type'].value_counts().index

profile_sr_leadtype = pd.pivot_table(cd_profile,
                             index='lead_type',
                             columns='sr_id',
                             values='seller_id',
                             aggfunc='count',
                             fill_value=0)
profile_sr_leadtype = profile_sr_leadtype.reindex(index)[cols]
profile_sr_leadtype

sr_id,4ef15afb4b2723d8f3d81e51ec7afefe,85fc447d336637ba1df43e793199fbc8,6565aa9ce3178a5caf6171827af3a9ba,d3d1e91a157ea7f90548eef82f1955e3,2695de1affa7750089c0455f8ce27021,de63de0d10a6012430098db33c679b0b,495d4e95a8cf8bbf8b432b612a2aa328,fbf4aef3f6915dc0c3c97d6812522f6a,068066e24f0c643eb1d089c7dd20cd73,c638112b43f1d1b86dcabb0da720c901,...,9e4d1098a3b0f5da39b0bc48f9876645,9ae085775a198122c5586fa830ff7f2b,56bf83c4bb35763a51c2baab501b4c67,34d40cdaf94010a1d05b0d6212f9e909,4b339f9567d060bcea4f5136b9f5949e,9749123c950bf8363ace42cb1c2d0815,9d12ef1a7eca3ec58c545c678af7869c,0a0fb2b07d841f84fb6714e35c723075,6aa3b86a83d784b05f0e37e26b20860d,b90f87164b5f8c2cfa5c8572834dbe3f
online_medium,36,19,29,17,15,22,19,23,11,9,...,11,7,9,4,5,2,3,0,1,1
online_big,16,13,8,13,9,7,12,5,3,3,...,4,3,2,1,2,1,0,0,0,0
industry,13,13,5,9,3,7,9,7,2,4,...,5,5,1,1,2,2,0,0,0,0
offline,16,6,7,4,12,8,3,4,7,3,...,0,2,5,2,0,1,2,0,0,0
online_small,7,5,3,6,8,5,3,2,2,3,...,2,2,2,0,0,1,1,0,0,0
online_beginner,4,5,3,4,5,3,0,0,0,2,...,1,4,4,1,0,0,0,0,0,0
online_top,2,2,0,1,1,1,0,2,0,0,...,1,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [23]:
###Key takeaways on SR on the lead side
# - 1st and 5th SR works good on offline compared to the rest.
# - 1st and 3rd SR is unparalled in online_medium category.
# - 1st 2nd 4th and 7th SR works well in the online_big category

In [24]:
###Predicting Leads which have a chance to convert
total_leads = marketing_qualified_leads.merge(closed_deals, how='left',left_on='mql_id',right_on='mql_id')

In [25]:
total_leads['converted_flag'] = np.where(total_leads['won_date'].isna(),0,1)

In [26]:
total_leads['converted_flag'].value_counts()

0    7158
1     842
Name: converted_flag, dtype: int64

In [27]:
###Out of a 8000, 842 leads have converted.Let's explore the data and look at some behaviour of converted leads.
converted_leads = total_leads[total_leads['converted_flag'] == 1]
converted_leads['origin'].value_counts()

organic_search       271
paid_search          195
unknown              179
social                75
direct_traffic        56
referral              24
email                 15
display                6
other                  4
other_publicities      3
Name: origin, dtype: int64

In [28]:
converted_leads['won_date'] = pd.to_datetime(converted_leads['won_date'])
converted_leads['first_contact_date'] = pd.to_datetime(converted_leads['first_contact_date'])

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [29]:
###Looks like organic and paid search are the best lead scourcs for conversion.Not surprising though
##We can build a predictive model for lead conversion but wwe do not have any negative samples in the dataset for that.
##We will be identifying leads which have a higher chance of conversion base on the time to convert and SR assigned.
converted_leads['time_to_convert'] = (converted_leads['won_date'] - converted_leads['first_contact_date']).dt.days

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [30]:
print('Avg time to convert {}'.format(converted_leads.time_to_convert.mean()))
print('Min time to convert {}'.format(converted_leads.time_to_convert.min()))
print('Max time to convert {}'.format(converted_leads.time_to_convert.max()))

Avg time to convert 48.44061757719715
Min time to convert -2
Max time to convert 427

In [31]:
###It takes an average of 48 days for a lead to convert. We can look at the outliers on this data and see which lead has gone beyond that
converted_leads = converted_leads[converted_leads['time_to_convert']>=0]
###We should also look at SR level i.e. how long is an SR taking to close the lead and his outliers
sr_convert = converted_leads.groupby('sr_id')['time_to_convert'].mean()

In [32]:
sr_convert.reset_index(drop=True)

0      25.218750
1     122.333333
2     306.000000
3      48.389831
4     172.000000
5      49.403226
6     180.555556
7      30.488722
8      55.125000
9      25.783784
10    321.000000
11     33.703125
12    234.000000
13     41.705882
14    214.333333
15     17.000000
16     96.653846
17    175.000000
18     22.388889
19     46.646341
20     61.735849
21     21.966102
Name: time_to_convert, dtype: float64

In [33]:
###Origin level conversion time
source_convert = converted_leads.groupby('origin')['time_to_convert'].mean()
source_convert
###Social takes a longer conversion time convert

origin
direct_traffic       31.125000
display              10.333333
email                52.200000
organic_search       50.192593
other                15.250000
other_publicities    39.333333
paid_search          56.600000
referral             32.541667
social               60.960000
unknown              41.290503
Name: time_to_convert, dtype: float64

In [34]:
###Using IQR to find outliers
q1 = converted_leads['time_to_convert'].quantile(0.25)
q3 = converted_leads['time_to_convert'].quantile(0.75)
IQR = q3-q1
###Upper quartile range
qr = converted_leads.time_to_convert.mean() + (q3 + 1.5*q1)
qr

111.00059453032105

In [35]:
# We got 62.5 days as IQR..this does not look great as only 194 leads are converted before 62.5 days.So we are taking
# 300 days as time to convert and if any lead goes beyond that....they are not converted.
# This way we can use this for modelling.All leads which are past 300 days and are not converted can be used for modelling
today = pd.datetime.now().date()
today

datetime.date(2019, 12, 3)

In [36]:
len(converted_leads[converted_leads['time_to_convert'] > 111])

124

In [37]:
not_converted_leads = total_leads[total_leads['converted_flag'] == 0]

In [38]:
not_converted_leads['won_date'] = pd.datetime.now()
not_converted_leads['first_contact_date'] = pd.to_datetime(not_converted_leads['first_contact_date'])
not_converted_leads['time_to_convert'] = (not_converted_leads['won_date'] - not_converted_leads['first_contact_date']).dt.days

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [39]:
not_converted_leads[not_converted_leads.time_to_convert<200]

Empty DataFrame
Columns: [mql_id, first_contact_date, landing_page_id, origin, seller_id, sdr_id, sr_id, won_date, business_segment, lead_type, lead_behaviour_profile, has_company, has_gtin, average_stock, business_type, declared_product_catalog_size, declared_monthly_revenue, converted_flag, time_to_convert]
Index: []

In [40]:
###We see that there are no converted leads beyond days 200 in cases they are not converted so modelling the data is not desirable
##So time is an important factor and we should convert the leads as early as possible
## Based on the above analysis we see that if the lead time goes beyond 111 days which is your IQR outlier
## There is 85% chance that it drops.(15% of converted leads are beyond 111 days)

In [41]:
###LTV calculations
###For converted seller, we take the transcations (price+shipping) for LTV calculations for the platform
###Getting the transactional data for the dealers
total_sales_seller = closed_deals.merge(order_items,how='left', left_on='seller_id',right_on='seller_id')

In [42]:
total_sales_seller.head()

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue,order_id,order_item_id,product_id,price,freight_value
0,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0,1efcc6ba75b519535a510c53153a9256,1.0,e94df75b2e9a8b056be0c144a731f55c,94.2,18.76
1,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0,d8d281c1a1398a1e835fdc4adfb81e2a,1.0,9e0873e9ac04b12f282b81af5daebd2e,664.0,38.41
2,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0,e5858127da61f07285827883e605254b,1.0,9bb2d066e4b33b624cbdfec7d50b3dcb,99.8,15.00
3,a555fb36b9368110ede0f043dfc3b9a0,bbb7d7893a450660432ea6652310ebb7,09285259593c61296eef10c734121d5b,d3d1e91a157ea7f90548eef82f1955e3,2018-05-08 20:17:59,car_accessories,industry,eagle,NaN,NaN,NaN,reseller,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,327174d3648a2d047e8940d7d15204ca,612170e34b97004b3ba37eae81836b4c,b90f87164b5f8c2cfa5c8572834dbe3f,6565aa9ce3178a5caf6171827af3a9ba,2018-06-05 17:27:23,home_appliances,online_big,cat,NaN,NaN,NaN,reseller,NaN,0.0,0475d054d40280dfba750663c9ad7a0a,1.0,a86859b91d632c991b914aead6ec8ad4,49.9,13.69

In [43]:
###Assuming these are sales till today since won data.We will be calclating LTV on that basis
total_sales_seller['won_date'] = pd.to_datetime(total_sales_seller['won_date'])
total_sales_seller['till_date'] = pd.datetime.now()

In [44]:
###Till_date_sales
total_sales_seller['no_of_days_till_date'] = total_sales_seller['till_date'] - total_sales_seller['won_date']
total_sales_seller['sales_price'] = total_sales_seller['price'] + total_sales_seller['freight_value']
agg_func = {'sales_price' : 'sum',
           'product_id':'count'}###To get total items
total_sales_grouped = total_sales_seller.groupby('seller_id').agg(agg_func).reset_index()
total_sales_grouped['average_purchase_value'] = total_sales_grouped['sales_price']/total_sales_grouped['product_id']

In [45]:
###Total frequency rate can be determined by number of distinct orders of each sellers
###Calculating distinct orders for each seller
total_orders_unique = total_sales_seller.groupby(['seller_id','order_id']).size().reset_index().rename(columns={0:'count'})
total_orders_seller = total_orders_unique.groupby('seller_id')['order_id'].count().reset_index().rename(columns={'order_id':'total_orders'})

In [46]:
###calculating frequency of orders. DIviding by number of days for total orders.
total_sales_grouped = total_sales_grouped.merge(total_orders_seller, how = 'left',left_on='seller_id',right_on='seller_id')
total_sales_seller = total_sales_seller[['seller_id','no_of_days_till_date']].groupby(['seller_id','no_of_days_till_date']).size().reset_index()
total_sales_grouped = total_sales_grouped.merge(total_sales_seller,
                                               how = 'left',left_on='seller_id',right_on='seller_id')

In [49]:
total_sales_grouped.columns

Index([             'seller_id',             'product_id',
                  'sales_price', 'average_purchase_value',
                 'total_orders',   'no_of_days_till_date',
                              0],
      dtype='object')

In [50]:
###Calculating frequency 
oneday = pd.Timedelta(days=1)
total_sales_grouped['frequency_rate'] = total_sales_grouped['total_orders']/(total_sales_grouped['no_of_days_till_date']/oneday)

In [52]:
###Assuming an e-commerce seller stays in business for 5 years
total_sales_grouped['LTV'] = total_sales_grouped['average_purchase_value']*total_sales_grouped['frequency_rate']*365*5

In [55]:
total_sales_grouped[['seller_id','LTV']].to_csv('LTV_values')